# Generated by Django 4.2.4 on 2023-08-18 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('respublicaapi', '0002_tools_delete_person_delete_species'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tools',
        ),
    ]
