# Generated by Django 4.2.4 on 2023-08-19 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('respublicaapi', '0006_rename_title_constitutionalcouncil_role_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='constitutionalcouncil',
            old_name='biography',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='europeanparliament',
            old_name='biography',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='government',
            old_name='biography',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='nationalassembly',
            old_name='biography',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='senat',
            old_name='biography',
            new_name='description',
        ),
    ]
