# Generated by Django 4.2.4 on 2023-08-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respublicaapi', '0007_rename_biography_constitutionalcouncil_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='government',
            name='additional_mandate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='government',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='government',
            name='mandate_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='government',
            name='picture',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
