# Generated by Django 4.2.4 on 2023-08-19 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respublicaapi', '0008_alter_government_additional_mandate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constitutionalcouncil',
            name='additional_mandate',
        ),
        migrations.RemoveField(
            model_name='constitutionalcouncil',
            name='party',
        ),
        migrations.AddField(
            model_name='constitutionalcouncil',
            name='nominator',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='constitutionalcouncil',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='constitutionalcouncil',
            name='mandate_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='constitutionalcouncil',
            name='picture',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='europeanparliament',
            name='additional_mandate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='europeanparliament',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='europeanparliament',
            name='mandate_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='europeanparliament',
            name='picture',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nationalassembly',
            name='additional_mandate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='nationalassembly',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='nationalassembly',
            name='mandate_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nationalassembly',
            name='picture',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='senat',
            name='additional_mandate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='senat',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='senat',
            name='mandate_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='senat',
            name='picture',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
